{% set name = "pwdlib" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a1d8a8fa09a2f7ebf208265e55d7d008103cbdc82b9e4902ffdd1ade91add5e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-regex-commit
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}

test:
  imports:
    - pwdlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frankie567/pwdlib
  summary: Modern password hashing for Python.
  doc_url: https://frankie567.github.io/pwdlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
    - frankie567
    - thewchan
